# Generated by Django 5.2.8 on 2025-12-29 22:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carro_alugado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(auto_now_add=True)),
                ('data_vencida', models.DateField(default=datetime.date(2026, 1, 12))),
                ('retorno', models.BooleanField(default=False)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
