# Generated by Django 5.2.8 on 2025-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('total_modelos', models.PositiveIntegerField(default=1)),
                ('total_disponivel', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
