# Generated by Django 5.2.8 on 2026-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
    ]
