# Generated by Django 5.2.8 on 2026-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cliente_rename_usuario_aluguel_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
