# Generated by Django 5.2.8 on 2026-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_aluguel_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
