# Generated by Django 5.2.8 on 2026-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_carro_valor_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='assinatura_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
