# Generated by Django 5.2.8 on 2026-05-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_aluguel_assinatura_cliente_aluguel_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='assinatura_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
